version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      # Restore cached dependencies if possible
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install --save-dev
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test:cover
          environment:
            JEST_JUNIT_OUTPUT: "coverage/junit-results.xml"
      - run:
          name: Upload test cover report to coveralls
          command: npm run coveralls 
      - store_test_results:
          path: coverage/
      - store_artifacts:
          path: coverage/
        